last_hashes:
  df: 4427417d687f5c361571e271dcfdd8d2
  df2: 4427417d687f5c361571e271dcfdd8d2
  df3: 4427417d687f5c361571e271dcfdd8d2
  simple-example: cdb2567f2ed82aaabf9fa6c1bb2cce1e
last_package: metapack+file:///Users/eric/proj/data-projects/metatab-packages/example-collection/staging/example-ipynb/_packages/example_data_package-2017-us-1/metadata.csv
